### PR TITLE
Add .twig support

### PR DESCRIPTION
**Pull request by ahmedelgabri**
Just adding [`.twig`](http://twig.sensiolabs.org/) support

### CODE REVIEW

**Comment by BenoitZugmeyer** [comment]
Thank you

**Comment by ahmedelgabri** [comment]
@BenoitZugmeyer any info when a new release will be on npm with this PR?

**Comment by BenoitZugmeyer** [comment]
Soon I guess, but I would love some feedback on #20 first. Anyway, I'll make a release this week-end at the latest.

**Comment by ahmedelgabri** [comment]
Cool, thanks!

**Pull request merged**
